[tool.poetry]
name = "rabbit"
version = "0.1.0"
description = ""
authors = ["Andrei Boyanov <andrei.boyanov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pika = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
